### ISSUE TITLE
Favorites on Home page

### ISSUE THREAD

**Issue by jschellerMC** [MassiveNerds/RetroMatic#28]
When I view Home, I only see retro's I have created.  I'd like to be able to "favorite" or "like" retromatic pages that I have viewed, even if I didn't start them.

I'm trying to start people in the habit of creating retromatic pages early and dropping notes into them as you go, but that requires someone to create the retro, save the link, and repeatedly post the link so others can find it.

**Comment by wordythebyrd** [comment]
@jschellerMC I added this feature. :)
